name: Jellyfin Proxy
version: "0.1"
panel_icon: "mdi:filmstrip"
panel_title: Jellyfin
slug: jellyfin-proxy
description: Proxy addon for Jellyfin
url: "https://github.com/grayda/ha-addons"
startup: application
boot: auto
webui: "http://[HOST]:[PORT:8096]/"
watchdog: "http://[HOST]:[PORT:8096]/"
ingress: true
ingress_port: 8096
ingress_entry: /
panel_admin: false
ports:
  8096/tcp: 8096
ports_description:
  8096/tcp: Web interface (Not required for Hass.io Ingress)
host_network: false
devices: []
usb: false
tmpfs: false
full_access: false
environment: {}
options:
  server: "http://jellyfin.local:8096"
  proxy_pass_host: true
schema:
  server: "match(^https?://.+:\\d+$)"
  proxy_pass_host: bool
services: []
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map: []
